# Example: Environment Variables
# This file should be encrypted with: just secrets:edit secrets/examples/environment.sops.yaml

development:
  # Database connections
  DATABASE_URL: "postgresql://username:password@localhost:5432/myapp_dev"
  REDIS_URL: "redis://localhost:6379/0"
  
  # API keys
  OPENAI_API_KEY: "sk-REPLACE_WITH_YOUR_OPENAI_KEY"
  STRIPE_SECRET_KEY: "sk_test_REPLACE_WITH_YOUR_STRIPE_TEST_KEY"
  STRIPE_PUBLISHABLE_KEY: "pk_test_REPLACE_WITH_YOUR_STRIPE_TEST_KEY"
  
  # Authentication
  JWT_SECRET: "your-super-secret-jwt-signing-key"
  SESSION_SECRET: "your-super-secret-session-key"
  
  # External services
  AWS_ACCESS_KEY_ID: "AKIAIOSFODNN7EXAMPLE"
  AWS_SECRET_ACCESS_KEY: "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
  AWS_REGION: "us-west-2"

production:
  # Production database (different from dev)
  DATABASE_URL: "postgresql://produser:prodpass@prod-db.amazonaws.com:5432/myapp"
  REDIS_URL: "redis://prod-redis.amazonaws.com:6379/0"
  
  # Production API keys
  OPENAI_API_KEY: "sk-REPLACE_WITH_YOUR_PRODUCTION_OPENAI_KEY"
  STRIPE_SECRET_KEY: "sk_live_REPLACE_WITH_YOUR_STRIPE_LIVE_KEY"
  STRIPE_PUBLISHABLE_KEY: "pk_live_REPLACE_WITH_YOUR_STRIPE_LIVE_KEY"
  
  # Production secrets (should be different from dev)
  JWT_SECRET: "different-production-jwt-secret"
  SESSION_SECRET: "different-production-session-secret"
  
  # Production AWS
  AWS_ACCESS_KEY_ID: "AKIAIOSFODNN7PRODEXAMPLE"
  AWS_SECRET_ACCESS_KEY: "prodJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
  AWS_REGION: "us-east-1"

common:
  # Non-sensitive but environment-specific values
  APP_NAME: "MyApplication"
  LOG_LEVEL: "info"
  PORT: "3000"