# Example: SSH Configuration
# This file should be encrypted with: just secrets:edit secrets/examples/ssh-config.sops.yaml

ssh_config: |
  # GitHub SSH configuration
  Host github.com
    HostName github.com
    User git
    IdentityFile ~/.ssh/id_ed25519
    AddKeysToAgent yes
    UseKeychain yes
  
  # Personal server
  Host personal-server
    HostName your-server.com
    User yourusername
    Port 22
    IdentityFile ~/.ssh/personal_key
    ForwardAgent yes
  
  # Work server
  Host work-server
    HostName work.company.com  
    User work-username
    Port 2222
    IdentityFile ~/.ssh/work_key
    ProxyJump bastion.company.com
  
  # Development environment
  Host dev-env
    HostName dev.company.com
    User developer
    IdentityFile ~/.ssh/dev_key
    LocalForward 3000 localhost:3000
    LocalForward 5432 localhost:5432

ssh_keys:
  # SSH private keys (base64 encoded)
  personal_key: |
    LS0tLS1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0=
    # Replace with your actual base64-encoded private key
    
  work_key: |
    LS0tLS1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0=
    # Replace with your actual base64-encoded private key