# Tokyo Night Storm Theme for Alacritty
# A darker variant of Tokyo Night

[colors.primary]
background = '#24283b'
foreground = '#c0caf5'

# Normal colors
[colors.normal]
black = '#1d202f'
red = '#f7768e'
green = '#9ece6a'
yellow = '#e0af68'
blue = '#7aa2f7'
magenta = '#bb9af7'
cyan = '#7dcfff'
white = '#a9b1d6'

# Bright colors
[colors.bright]
black = '#414868'
red = '#f7768e'
green = '#9ece6a'
yellow = '#e0af68'
blue = '#7aa2f7'
magenta = '#bb9af7'
cyan = '#7dcfff'
white = '#c0caf5'

[colors.selection]
background = '#364a82'
foreground = '#c0caf5'

[colors.cursor]
cursor = '#c0caf5'
text = '#24283b'