# Tokyo Night Light Theme for Alacritty
# Light variant of Tokyo Night

[colors.primary]
background = '#d5d6db'
foreground = '#565a6e'

# Normal colors
[colors.normal]
black = '#0f0f14'
red = '#8c4351'
green = '#33635c'
yellow = '#8f5e15'
blue = '#34548a'
magenta = '#5a4a78'
cyan = '#0f4b6e'
white = '#343b59'

# Bright colors
[colors.bright]
black = '#9699a3'
red = '#8c4351'
green = '#33635c'
yellow = '#8f5e15'
blue = '#34548a'
magenta = '#5a4a78'
cyan = '#0f4b6e'
white = '#343b59'

[colors.selection]
background = '#99a1b3'
foreground = '#343b59'

[colors.cursor]
cursor = '#343b59'
text = '#d5d6db'