# Alacritty Terminal Configuration
# Tokyo Night Theme with CaskaydiaMono Nerd Font

[env]
TERM = "xterm-256color"

[window]
decorations = "transparent"
blur = true
dynamic_padding = true

[font]
normal = { family = "FiraCode Nerd Font", style = "Regular" }
bold = { family = "FiraCode Nerd Font", style = "Bold" }
italic = { family = "FiraCode Nerd Font", style = "Italic" }
bold_italic = { family = "FiraCode Nerd Font", style = "Bold Italic" }
size = 14

# Tokyo Night Color Scheme
[colors.primary]
background = '#1E1E1E'
foreground = '#D0D0D0'

# Normal colors
[colors.normal]
black = '#000000'
red = '#FF5F56'
green = '#27C93F'
yellow = '#FFBD2E'
blue = '#268BD2'
magenta = '#AF00FF'
cyan = '#2AA198'
white = '#EAEAEA'

# Bright colors
[colors.bright]
black = '#555555'
red = '#FF5F56'
green = '#27C93F'
yellow = '#FFBD2E'
blue = '#268BD2'
magenta = '#AF00FF'
cyan = '#2AA198'
white = '#FFFFFF'

[colors.selection]
background = '#283457'
foreground = '#a9b1d6'

[colors.cursor]
cursor = '#a9b1d6'
text = '#1a1b26'

# Search colors
[colors.search.matches]
foreground = '#1a1b26'
background = '#e0af68'

[colors.search.focused_match]
foreground = '#1a1b26'
background = '#9ece6a'

# Keyboard bindings
[keyboard]
bindings = [
  # Toggle fullscreen
  { key = "F11", action = "ToggleFullscreen" },
  
  # Scrolling
  { key = "PageUp", mods = "Shift", action = "ScrollPageUp" },
  { key = "PageDown", mods = "Shift", action = "ScrollPageDown" },
  { key = "Home", mods = "Shift", action = "ScrollToTop" },
  { key = "End", mods = "Shift", action = "ScrollToBottom" },
  
  # Font size
  { key = "Plus", mods = "Control", action = "IncreaseFontSize" },
  { key = "Minus", mods = "Control", action = "DecreaseFontSize" },
  { key = "Key0", mods = "Control", action = "ResetFontSize" },
  
  # Copy/Paste
  { key = "C", mods = "Control|Shift", action = "Copy" },
  { key = "V", mods = "Control|Shift", action = "Paste" },
]

[cursor]
style = { shape = "Block", blinking = "Off" }
unfocused_hollow = true

[selection]
save_to_clipboard = true

[scrolling]
history = 10000
multiplier = 3

[bell]
animation = "EaseOutExpo"
duration = 0
color = "#ffffff"

# Mouse
[mouse]
hide_when_typing = true